<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory).build\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory).build\obj\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
